# Generated by Django 4.2.9 on 2024-01-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_portfolio_project_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='sumary',
            new_name='summary',
        ),
    ]
