# Generated by Django 4.2.9 on 2024-01-21 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_rename_links_link_rename_skills_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
