# Generated by Django 4.2.9 on 2024-01-21 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_alter_myinfo_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
