# Generated by Django 4.2.9 on 2024-01-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_skill_knowledge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='date',
            new_name='email',
        ),
        migrations.AddField(
            model_name='summary',
            name='phone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
