# Generated by Django 4.2.9 on 2024-01-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_rename_date_summary_email_summary_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('filter-app', 'App'), ('filter-card', 'Card'), ('filter-web', 'Web')], max_length=255),
        ),
        migrations.AlterField(
            model_name='summary',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
